spring:
  h2: # h2
    console:
      enabled: true
      path: /h2
  datasource: # datasource
    url: "jdbc:h2:./TREINAMENTODATA"
    driver-class-name: org.h2.Driver
    username: sa
  jpa: # JPA
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080
  servlet:
    context-path: /api